name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project:latest
      -
         name: Deploy image
         run: kubectl apply -f deployment-script-app.yml 
        
        # id: install-kubectl
        # uses: jtalk/k8s-deploy@v2
        # with:
        #   namespace: 'myapp'
        #   manifests: |
        #       deployment-script-app.yml
        #   images: '${{ secrets.DOCKERHUB_USERNAME }}/project:latest'
        #   kubectl-version: 'latest'
